using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Barjees.Common
{
    /// <summary>
    /// Represents a move for a pawn generated by a roll result
    /// </summary>
    public class PawnMove
    {
        /// <summary>
        /// Parent roll result
        /// </summary>
        public RollResult Parent { get; set; }
        /// <summary>
        /// The value of the move
        /// </summary>
        public int Value { get; set; }
        /// <summary>
        /// Gets or sets the move usage flag
        /// </summary>
        public bool IsUsed { get; set; }

        /// <summary>
        /// Default constructor
        /// </summary>
        public PawnMove()
        {
            IsUsed = false;
            Value = 0;
        }

    }
}
